version: '3.8'

services:
  backend:
    build: ./backend
    container_name: suffoclix-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: Root@1234
      DB_NAME: ott_platform
      JWT_SECRET: suffoclix_super_secret_key_2024
      JWT_EXPIRES_IN: 7d
      RAZORPAY_KEY_ID: rzp_test_T6eG82d77YJ7UR
      RAZORPAY_KEY_SECRET: L7WAelU565IGwR3EZ6WikqyH
    volumes:
      - ./backend/uploads:/app/uploads
    network_mode: host